### ISSUE TITLE
The Eternal Cylinder (865680)

### ISSUE THREAD

**Issue by ExpandingMan** [ValveSoftware/Proton#6234]
# Compatibility Report
- The Eternal Cylinder
- 865680

## System Information
Output of `inxi -SMG`
```
System:
  Host: asus-desk-1 Kernel: 5.15.71-1-MANJARO arch: x86_64 bits: 64
    Desktop: Qtile v: 0.22.1 Distro: Manjaro Linux
Machine:
  Type: Desktop Mobo: ASUSTeK model: TUF GAMING X570-PLUS (WI-FI) v: Rev X.0x
    serial: <superuser required> UEFI-[Legacy]: American Megatrends v: 0807
    date: 07/08/2019
Graphics:
  Device-1: NVIDIA TU104 [GeForce RTX 2080 SUPER] driver: nvidia v: 515.76
  Display: x11 server: X.Org v: 21.1.4 driver: X: loaded: nvidia
    gpu: nvidia resolution: 1: 2560x1440~144Hz 2: 2560x1440~144Hz
  OpenGL: renderer: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 v: 4.6.0 NVIDIA
    515.76
```
My steam sysinfo can be found [here](https://gist.github.com/ExpandingMan/d1823b3ced1e060bfdf6bc2d726362e6).

Tried proton experimental latest and GE-37.

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
![image](https://user-images.githubusercontent.com/11379353/195991475-b1a9ca3c-2403-48a3-8ffb-92e3de722ac0.png)

It seems strange that it gets this error since this is a common dependency.  I was able to solve the problem by using a prefix with `vcredist2019` installed via bottles.  Game seems to run fine with DX12.  Perhaps it requires a later version of `vcredist` than proton will provision?  (I have no idea how protons provisioning works.)

## Reproduction
Just install and run as normal.
