### ISSUE TITLE
Street Fighter 6 Demo (2154900)

### ISSUE THREAD

**Issue by smec44** [ValveSoftware/Proton#6722]
# Compatibility Report
- Name of the game with compatibility issues: Street Fighter 6 Demo
- Steam AppID of the game: 2154900

## System Information
- GPU: GTX 1070
- Driver/LLVM version: Nvidia 530.41.03
- Kernel version: 6.2.12
- Link to full system information report as [Gist](https://gist.github.com/smec44/178a9c04c82eafa556c0d7d0ff5bb411):
- Proton version: experimental-8.0-20230426

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2154900.log](https://github.com/ValveSoftware/Proton/files/11348535/steam-2154900.log)

## Symptoms 
RE Engine splash doesn't display, presumably MF related

Some incorrect rendering. Luke's head was invisible once during World Tour training. Another time half his hair was missing. Luke's model was flickering another occasion. Other lighting issues.

![Screenshot_20230428_081721](https://user-images.githubusercontent.com/99881730/235008998-929aba63-1760-48a5-8a40-89858f02de3c.png)

Game freezes anywhere from 2-10 minutes in needing to be force quit.

## Reproduction

Play World Tour mode

**Comment by kisak-valve** [comment]
Rendering issue might be related to https://github.com/HansKristian-Work/vkd3d-proton/issues/1541.

**Comment by ex1tium** [comment]
Hello. I'm having problems playing online against other people in SF6 Open Beta. The steam client crashes as soon as I load into an online match which results in fight stick inputs stop working and within 30s the game will crash too.  There was no issue for Open Beta so I'm posting here.

It works fine when in training or playing against bots, but for example, just now when another player challenged me the steam crashed instantly upon loading to game. There are also some frame rate issues but nothing major. Latest Proton Experimental seems to have fixed graphics bugs from Demo version.

I ran steam client through command line on another monitor to see what's up and this is the output:

```
Installing breakpad exception handler for appid(steam)/version(1682708537)/tid(715106)
crash_20230521213832_64.dmp[715816]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230521213832_64.dmp
/home/ex1tium/.local/share/Steam/steam.sh: line 798: 705715 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"

    ~ ▓▒░··································································································································································░▒▓ took 16m 10s   at 21:38:33  
❯ crash_20230521213832_64.dmp[715816]: Finished uploading minidump (out-of-process): success = yes
crash_20230521213832_64.dmp[715816]: response: CrashID=bp-96254233-5fed-44b8-b29f-59eb82230521
crash_20230521213832_64.dmp[715816]: file ''/tmp/dumps/crash_20230521213832_64.dmp'', upload yes: ''CrashID=bp-96254233-5fed-44b8-b29f-59eb82230521''
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : Fatal assert; application exiting
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(708988)
assert_20230521213834_7.dmp[715885]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230521213834_7.dmp
assert_20230521213834_7.dmp[715885]: Finished uploading minidump (out-of-process): success = yes
assert_20230521213834_7.dmp[715885]: response: Discarded=1
assert_20230521213834_7.dmp[715885]: file ''/tmp/dumps/assert_20230521213834_7.dmp'', upload yes: ''Discarded=1''
CCrossProcessPipe::BWrite wrote too few bytes: 32 (Broken pipe).  Continuing.
src/common/pipes.cpp (885) : stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (885) : stalled cross-thread pipe (pipe is disconnected).
Installing breakpad exception handler for appid(wine64-preloader)/version(1.0)/tid(708653)
assert_20230521213909_3.dmp[716121]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230521213909_3.dmp
src/clientdll/steamclient.cpp (876) : bufRet.TellPut() == sizeof(uint8)
src/clientdll/steamclient.cpp (876) : bufRet.TellPut() == sizeof(uint8)
src/common/processpipe_posix.cpp (507) : CCrossProcessPipe::BWrite: 32 (Broken pipe)
src/common/processpipe_posix.cpp (507) : CCrossProcessPipe::BWrite: 32 (Broken pipe)
pid 708576 != 708575, skipping destruction (fork without exec?)
assert_20230521213909_3.dmp[716121]: Finished uploading minidump (out-of-process): success = yes
assert_20230521213909_3.dmp[716121]: response: Discarded=1
```

```
From Proton log:

Proton: 1684333320 experimental-8.0-20230517
SteamGameId: 1952120
Command: ['/run/media/ex1tium/GAMES/SteamLibrary/steamapps/common/Street Fighter 6 - Open Beta/StreetFighter6OpenBeta.exe']
Options: {'forcelgadd'}
depot: 0.20230424.48416
pressure-vessel: 0.20230418.0 scout
scripts: 0.20230418.0
sniper: 0.20230424.48416 sniper 0.20230424.48416
Kernel: Linux 6.2.14-300.fsync.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sun May  7 08:45:11 UTC 2023 x86_64
Language: LC_ALL None, LC_MESSAGES None, LC_CTYPE None
```

```
❯ inxi -Gxx
Graphics:
  Device-1: NVIDIA GA104 [GeForce RTX 3070] vendor: ASUSTeK driver: nvidia
    v: 525.116.03 arch: Ampere pcie: speed: 5 GT/s lanes: 16 ports: active: none
    off: DP-1, DP-2, DP-3, HDMI-A-1 empty: HDMI-A-2 bus-ID: 01:00.0
    chip-ID: 10de:2484
  Display: wayland server: X.org v: 1.20.14 with: Xwayland v: 22.1.7
    compositor: kwin_wayland driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa alternate: nv gpu: nvidia
    d-rect: 5720x4440 display-ID: 0
  Monitor-1: DP-1 pos: top-center res: 1920x1080 size: N/A
  Monitor-2: DP-2 pos: bottom-c res: 3440x1440 size: N/A
  Monitor-3: DP-3 pos: middle-r res: 1080x1920 size: N/A
  Monitor-4: HDMI-A-1 pos: middle-l res: 1200x1920 size: N/A
  API: OpenGL v: 4.6.0 NVIDIA 525.116.03 renderer: NVIDIA GeForce RTX
    3070/PCIe/SSE2 direct-render: Yes
```
When plugging in my fight stick.
```
Local Device Found
  type: 0010 0082
  path: sdl://2
  serial_number:  - 0
  Manufacturer: 
  Product:      Akishop Customs PS360+ v1.66
  Release:      111
  Interface:    -1

!! Steam controller device opened for index 1.
```

[steam-1952120.zip](https://github.com/ValveSoftware/Proton/files/11525336/steam-1952120.zip)

Above is my PROTON_LOG. Any clues what might be the cause?
