### ISSUE TITLE
Age of Mythology won't start (no crash) (266840)

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [ValveSoftware/Proton#763]
Age of Mythology won't start. Selecting "Bypass Launcher" does not help. The proton process shows up for a while and the game is shown as "running" but nothing happens.

Which logs do you need?

```
▶ inxi -GS
System:
  Host: XXX Kernel: 4.18.3-arch1-1-ARCH x86_64 bits: 64 
  Desktop: Xfce 4.12.4 Distro: Arch Linux 
Graphics:
  Card-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X] driver: amdgpu 
  v: kernel 
  Display: x11 server: X.Org 1.20.1 driver: ati,modesetting 
  resolution: 1920x1080~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: AMD Radeon RX 480 Graphics (POLARIS10 DRM 3.26.0 
  4.18.3-arch1-1-ARCH LLVM 6.0.1) 
  v: 4.5 Mesa 18.1.6 
```
